//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::vec_init_then_push)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;
use trident_fuzz::AccountDiscriminator;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: memebook
// ----------------------------------------------------------------------------
pub mod memebook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for memebook
    pub fn program_id() -> Pubkey {
        pubkey!("GGVLRegjz8K7op4KzJELS8GpEqHHCv7XagZBkEpCvsjh")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAdmin
    // ....................................................................

    /// Main instruction struct for AcceptAdmin
    pub struct AcceptAdminInstruction {
        pub accounts: AcceptAdminInstructionAccountMetas,
        pub data: AcceptAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAdminInstructionAccountMetas {
        pub pending_admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for AcceptAdmin instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAdminInstructionAccounts {
        pub pending_admin: Pubkey,

        pub config: Pubkey,
    }

    impl AcceptAdminInstructionAccounts {
        pub fn new(pending_admin: Pubkey, config: Pubkey) -> Self {
            Self {
                pending_admin,

                config,
            }
        }
    }

    /// Instruction data for AcceptAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAdminInstructionData {}

    impl AcceptAdminInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAdminInstruction
    impl AcceptAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [112u8, 42u8, 45u8, 90u8, 116u8, 181u8, 13u8, 170u8]
        }

        pub fn data(data: AcceptAdminInstructionData) -> Self {
            Self {
                accounts: AcceptAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAdminInstructionAccounts) -> Self {
            self.accounts.pending_admin = AccountMeta::new_readonly(accounts.pending_admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pending_admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AcceptOffer
    // ....................................................................

    /// Main instruction struct for AcceptOffer
    pub struct AcceptOfferInstruction {
        pub accounts: AcceptOfferInstructionAccountMetas,
        pub data: AcceptOfferInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptOffer instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptOfferInstructionAccountMetas {
        pub borrower: AccountMeta,

        pub config: AccountMeta,

        pub offer: AccountMeta,

        pub loan: AccountMeta,

        pub principal_mint: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub offer_vault: AccountMeta,

        pub loan_collateral_vault: AccountMeta,

        pub borrower_collateral_account: AccountMeta,

        pub borrower_principal_account: AccountMeta,

        pub fee_recipient: AccountMeta,

        pub fee_principal_account: AccountMeta,

        pub principal_token_program: AccountMeta,

        pub collateral_token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AcceptOffer instruction
    #[derive(Debug, Clone)]
    pub struct AcceptOfferInstructionAccounts {
        pub borrower: Pubkey,

        pub config: Pubkey,

        pub offer: Pubkey,

        pub loan: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub offer_vault: Pubkey,

        pub loan_collateral_vault: Pubkey,

        pub borrower_collateral_account: Pubkey,

        pub borrower_principal_account: Pubkey,

        pub fee_recipient: Pubkey,

        pub fee_principal_account: Pubkey,

        pub principal_token_program: Pubkey,

        pub collateral_token_program: Pubkey,
    }

    impl AcceptOfferInstructionAccounts {
        pub fn new(
            borrower: Pubkey,

            config: Pubkey,

            offer: Pubkey,

            loan: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            offer_vault: Pubkey,

            loan_collateral_vault: Pubkey,

            borrower_collateral_account: Pubkey,

            borrower_principal_account: Pubkey,

            fee_recipient: Pubkey,

            fee_principal_account: Pubkey,

            principal_token_program: Pubkey,

            collateral_token_program: Pubkey,
        ) -> Self {
            Self {
                borrower,

                config,

                offer,

                loan,

                principal_mint,

                collateral_mint,

                offer_vault,

                loan_collateral_vault,

                borrower_collateral_account,

                borrower_principal_account,

                fee_recipient,

                fee_principal_account,

                principal_token_program,

                collateral_token_program,
            }
        }
    }

    /// Instruction data for AcceptOffer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptOfferInstructionData {
        pub loan_id: u64,

        pub draw_amount: u64,
    }

    impl AcceptOfferInstructionData {
        pub fn new(loan_id: u64, draw_amount: u64) -> Self {
            Self {
                loan_id,

                draw_amount,
            }
        }
    }

    /// Implementation for AcceptOfferInstruction
    impl AcceptOfferInstruction {
        fn discriminator() -> [u8; 8] {
            [227u8, 82u8, 234u8, 131u8, 1u8, 18u8, 48u8, 2u8]
        }

        pub fn data(data: AcceptOfferInstructionData) -> Self {
            Self {
                accounts: AcceptOfferInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptOfferInstructionAccounts) -> Self {
            self.accounts.borrower = AccountMeta::new(accounts.borrower, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.offer = AccountMeta::new(accounts.offer, false);

            self.accounts.loan = AccountMeta::new(accounts.loan, false);

            self.accounts.principal_mint =
                AccountMeta::new_readonly(accounts.principal_mint, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.offer_vault = AccountMeta::new(accounts.offer_vault, false);

            self.accounts.loan_collateral_vault =
                AccountMeta::new(accounts.loan_collateral_vault, false);

            self.accounts.borrower_collateral_account =
                AccountMeta::new(accounts.borrower_collateral_account, false);

            self.accounts.borrower_principal_account =
                AccountMeta::new(accounts.borrower_principal_account, false);

            self.accounts.fee_recipient = AccountMeta::new_readonly(accounts.fee_recipient, false);

            self.accounts.fee_principal_account =
                AccountMeta::new(accounts.fee_principal_account, false);

            self.accounts.principal_token_program =
                AccountMeta::new_readonly(accounts.principal_token_program, false);

            self.accounts.collateral_token_program =
                AccountMeta::new_readonly(accounts.collateral_token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.borrower.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.offer.clone());

            metas.push(self.accounts.loan.clone());

            metas.push(self.accounts.principal_mint.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.offer_vault.clone());

            metas.push(self.accounts.loan_collateral_vault.clone());

            metas.push(self.accounts.borrower_collateral_account.clone());

            metas.push(self.accounts.borrower_principal_account.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.push(self.accounts.fee_principal_account.clone());

            metas.push(self.accounts.principal_token_program.clone());

            metas.push(self.accounts.collateral_token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelOffer
    // ....................................................................

    /// Main instruction struct for CancelOffer
    pub struct CancelOfferInstruction {
        pub accounts: CancelOfferInstructionAccountMetas,
        pub data: CancelOfferInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelOffer instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelOfferInstructionAccountMetas {
        pub lender: AccountMeta,

        pub offer: AccountMeta,

        pub principal_mint: AccountMeta,

        pub offer_vault: AccountMeta,

        pub lender_principal_account: AccountMeta,

        pub principal_token_program: AccountMeta,
    }

    /// Account pubkeys for CancelOffer instruction
    #[derive(Debug, Clone)]
    pub struct CancelOfferInstructionAccounts {
        pub lender: Pubkey,

        pub offer: Pubkey,

        pub principal_mint: Pubkey,

        pub offer_vault: Pubkey,

        pub lender_principal_account: Pubkey,

        pub principal_token_program: Pubkey,
    }

    impl CancelOfferInstructionAccounts {
        pub fn new(
            lender: Pubkey,

            offer: Pubkey,

            principal_mint: Pubkey,

            offer_vault: Pubkey,

            lender_principal_account: Pubkey,

            principal_token_program: Pubkey,
        ) -> Self {
            Self {
                lender,

                offer,

                principal_mint,

                offer_vault,

                lender_principal_account,

                principal_token_program,
            }
        }
    }

    /// Instruction data for CancelOffer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelOfferInstructionData {}

    impl CancelOfferInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelOfferInstruction
    impl CancelOfferInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 203u8, 223u8, 40u8, 92u8, 89u8, 53u8, 119u8]
        }

        pub fn data(data: CancelOfferInstructionData) -> Self {
            Self {
                accounts: CancelOfferInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelOfferInstructionAccounts) -> Self {
            self.accounts.lender = AccountMeta::new(accounts.lender, true);

            self.accounts.offer = AccountMeta::new(accounts.offer, false);

            self.accounts.principal_mint =
                AccountMeta::new_readonly(accounts.principal_mint, false);

            self.accounts.offer_vault = AccountMeta::new(accounts.offer_vault, false);

            self.accounts.lender_principal_account =
                AccountMeta::new(accounts.lender_principal_account, false);

            self.accounts.principal_token_program =
                AccountMeta::new_readonly(accounts.principal_token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.lender.clone());

            metas.push(self.accounts.offer.clone());

            metas.push(self.accounts.principal_mint.clone());

            metas.push(self.accounts.offer_vault.clone());

            metas.push(self.accounts.lender_principal_account.clone());

            metas.push(self.accounts.principal_token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimDefault
    // ....................................................................

    /// Main instruction struct for ClaimDefault
    pub struct ClaimDefaultInstruction {
        pub accounts: ClaimDefaultInstructionAccountMetas,
        pub data: ClaimDefaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimDefault instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimDefaultInstructionAccountMetas {
        pub lender: AccountMeta,

        pub borrower: AccountMeta,

        pub fee_recipient: AccountMeta,

        pub config: AccountMeta,

        pub loan: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub loan_collateral_vault: AccountMeta,

        pub lender_collateral_account: AccountMeta,

        pub fee_collateral_account: AccountMeta,

        pub collateral_token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimDefault instruction
    #[derive(Debug, Clone)]
    pub struct ClaimDefaultInstructionAccounts {
        pub lender: Pubkey,

        pub borrower: Pubkey,

        pub fee_recipient: Pubkey,

        pub config: Pubkey,

        pub loan: Pubkey,

        pub collateral_mint: Pubkey,

        pub loan_collateral_vault: Pubkey,

        pub lender_collateral_account: Pubkey,

        pub fee_collateral_account: Pubkey,

        pub collateral_token_program: Pubkey,
    }

    impl ClaimDefaultInstructionAccounts {
        pub fn new(
            lender: Pubkey,

            borrower: Pubkey,

            fee_recipient: Pubkey,

            config: Pubkey,

            loan: Pubkey,

            collateral_mint: Pubkey,

            loan_collateral_vault: Pubkey,

            lender_collateral_account: Pubkey,

            fee_collateral_account: Pubkey,

            collateral_token_program: Pubkey,
        ) -> Self {
            Self {
                lender,

                borrower,

                fee_recipient,

                config,

                loan,

                collateral_mint,

                loan_collateral_vault,

                lender_collateral_account,

                fee_collateral_account,

                collateral_token_program,
            }
        }
    }

    /// Instruction data for ClaimDefault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimDefaultInstructionData {}

    impl ClaimDefaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimDefaultInstruction
    impl ClaimDefaultInstruction {
        fn discriminator() -> [u8; 8] {
            [12u8, 132u8, 209u8, 37u8, 163u8, 22u8, 128u8, 241u8]
        }

        pub fn data(data: ClaimDefaultInstructionData) -> Self {
            Self {
                accounts: ClaimDefaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimDefaultInstructionAccounts) -> Self {
            self.accounts.lender = AccountMeta::new(accounts.lender, true);

            self.accounts.borrower = AccountMeta::new(accounts.borrower, false);

            self.accounts.fee_recipient = AccountMeta::new(accounts.fee_recipient, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.loan = AccountMeta::new(accounts.loan, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.loan_collateral_vault =
                AccountMeta::new(accounts.loan_collateral_vault, false);

            self.accounts.lender_collateral_account =
                AccountMeta::new(accounts.lender_collateral_account, false);

            self.accounts.fee_collateral_account =
                AccountMeta::new(accounts.fee_collateral_account, false);

            self.accounts.collateral_token_program =
                AccountMeta::new_readonly(accounts.collateral_token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.lender.clone());

            metas.push(self.accounts.borrower.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.loan.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.loan_collateral_vault.clone());

            metas.push(self.accounts.lender_collateral_account.clone());

            metas.push(self.accounts.fee_collateral_account.clone());

            metas.push(self.accounts.collateral_token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateOffer
    // ....................................................................

    /// Main instruction struct for CreateOffer
    pub struct CreateOfferInstruction {
        pub accounts: CreateOfferInstructionAccountMetas,
        pub data: CreateOfferInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateOffer instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateOfferInstructionAccountMetas {
        pub lender: AccountMeta,

        pub config: AccountMeta,

        pub offer: AccountMeta,

        pub principal_mint: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub offer_vault: AccountMeta,

        pub lender_principal_account: AccountMeta,

        pub principal_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateOffer instruction
    #[derive(Debug, Clone)]
    pub struct CreateOfferInstructionAccounts {
        pub lender: Pubkey,

        pub config: Pubkey,

        pub offer: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub offer_vault: Pubkey,

        pub lender_principal_account: Pubkey,

        pub principal_token_program: Pubkey,
    }

    impl CreateOfferInstructionAccounts {
        pub fn new(
            lender: Pubkey,

            config: Pubkey,

            offer: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            offer_vault: Pubkey,

            lender_principal_account: Pubkey,

            principal_token_program: Pubkey,
        ) -> Self {
            Self {
                lender,

                config,

                offer,

                principal_mint,

                collateral_mint,

                offer_vault,

                lender_principal_account,

                principal_token_program,
            }
        }
    }

    /// Instruction data for CreateOffer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateOfferInstructionData {
        pub offer_id: u64,

        pub principal_total: u64,

        pub collateral_total: u64,

        pub min_draw: u64,

        pub apr_bps: u32,

        pub duration_seconds: u32,

        pub expiry_ts: i64,
    }

    impl CreateOfferInstructionData {
        pub fn new(
            offer_id: u64,

            principal_total: u64,

            collateral_total: u64,

            min_draw: u64,

            apr_bps: u32,

            duration_seconds: u32,

            expiry_ts: i64,
        ) -> Self {
            Self {
                offer_id,

                principal_total,

                collateral_total,

                min_draw,

                apr_bps,

                duration_seconds,

                expiry_ts,
            }
        }
    }

    /// Implementation for CreateOfferInstruction
    impl CreateOfferInstruction {
        fn discriminator() -> [u8; 8] {
            [237u8, 233u8, 192u8, 168u8, 248u8, 7u8, 249u8, 241u8]
        }

        pub fn data(data: CreateOfferInstructionData) -> Self {
            Self {
                accounts: CreateOfferInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateOfferInstructionAccounts) -> Self {
            self.accounts.lender = AccountMeta::new(accounts.lender, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.offer = AccountMeta::new(accounts.offer, false);

            self.accounts.principal_mint =
                AccountMeta::new_readonly(accounts.principal_mint, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.offer_vault = AccountMeta::new(accounts.offer_vault, false);

            self.accounts.lender_principal_account =
                AccountMeta::new(accounts.lender_principal_account, false);

            self.accounts.principal_token_program =
                AccountMeta::new_readonly(accounts.principal_token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.lender.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.offer.clone());

            metas.push(self.accounts.principal_mint.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.offer_vault.clone());

            metas.push(self.accounts.lender_principal_account.clone());

            metas.push(self.accounts.principal_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub payer: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub payer: Pubkey,

        pub config: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(payer: Pubkey, config: Pubkey) -> Self {
            Self { payer, config }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {
        pub admin: Pubkey,

        pub fee_recipient: Pubkey,

        pub origination_fee_bps: u16,

        pub interest_fee_bps: u16,

        pub default_fee_bps: u16,
    }

    impl InitializeConfigInstructionData {
        pub fn new(
            admin: Pubkey,

            fee_recipient: Pubkey,

            origination_fee_bps: u16,

            interest_fee_bps: u16,

            default_fee_bps: u16,
        ) -> Self {
            Self {
                admin,

                fee_recipient,

                origination_fee_bps,

                interest_fee_bps,

                default_fee_bps,
            }
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAdmin
    // ....................................................................

    /// Main instruction struct for ProposeAdmin
    pub struct ProposeAdminInstruction {
        pub accounts: ProposeAdminInstructionAccountMetas,
        pub data: ProposeAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAdminInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for ProposeAdmin instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAdminInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl ProposeAdminInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for ProposeAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAdminInstructionData {
        pub new_admin: Pubkey,
    }

    impl ProposeAdminInstructionData {
        pub fn new(new_admin: Pubkey) -> Self {
            Self { new_admin }
        }
    }

    /// Implementation for ProposeAdminInstruction
    impl ProposeAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [121u8, 214u8, 199u8, 212u8, 87u8, 39u8, 117u8, 234u8]
        }

        pub fn data(data: ProposeAdminInstructionData) -> Self {
            Self {
                accounts: ProposeAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAdminInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Repay
    // ....................................................................

    /// Main instruction struct for Repay
    pub struct RepayInstruction {
        pub accounts: RepayInstructionAccountMetas,
        pub data: RepayInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Repay instruction
    #[derive(Debug, Clone, Default)]
    pub struct RepayInstructionAccountMetas {
        pub borrower: AccountMeta,

        pub lender: AccountMeta,

        pub fee_recipient: AccountMeta,

        pub config: AccountMeta,

        pub loan: AccountMeta,

        pub principal_mint: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub loan_collateral_vault: AccountMeta,

        pub borrower_principal_account: AccountMeta,

        pub borrower_collateral_account: AccountMeta,

        pub lender_principal_account: AccountMeta,

        pub fee_principal_account: AccountMeta,

        pub principal_token_program: AccountMeta,

        pub collateral_token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Repay instruction
    #[derive(Debug, Clone)]
    pub struct RepayInstructionAccounts {
        pub borrower: Pubkey,

        pub lender: Pubkey,

        pub fee_recipient: Pubkey,

        pub config: Pubkey,

        pub loan: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub loan_collateral_vault: Pubkey,

        pub borrower_principal_account: Pubkey,

        pub borrower_collateral_account: Pubkey,

        pub lender_principal_account: Pubkey,

        pub fee_principal_account: Pubkey,

        pub principal_token_program: Pubkey,

        pub collateral_token_program: Pubkey,
    }

    impl RepayInstructionAccounts {
        pub fn new(
            borrower: Pubkey,

            lender: Pubkey,

            fee_recipient: Pubkey,

            config: Pubkey,

            loan: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            loan_collateral_vault: Pubkey,

            borrower_principal_account: Pubkey,

            borrower_collateral_account: Pubkey,

            lender_principal_account: Pubkey,

            fee_principal_account: Pubkey,

            principal_token_program: Pubkey,

            collateral_token_program: Pubkey,
        ) -> Self {
            Self {
                borrower,

                lender,

                fee_recipient,

                config,

                loan,

                principal_mint,

                collateral_mint,

                loan_collateral_vault,

                borrower_principal_account,

                borrower_collateral_account,

                lender_principal_account,

                fee_principal_account,

                principal_token_program,

                collateral_token_program,
            }
        }
    }

    /// Instruction data for Repay
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RepayInstructionData {}

    impl RepayInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RepayInstruction
    impl RepayInstruction {
        fn discriminator() -> [u8; 8] {
            [234u8, 103u8, 67u8, 82u8, 208u8, 234u8, 219u8, 166u8]
        }

        pub fn data(data: RepayInstructionData) -> Self {
            Self {
                accounts: RepayInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RepayInstructionAccounts) -> Self {
            self.accounts.borrower = AccountMeta::new(accounts.borrower, true);

            self.accounts.lender = AccountMeta::new(accounts.lender, false);

            self.accounts.fee_recipient = AccountMeta::new(accounts.fee_recipient, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.loan = AccountMeta::new(accounts.loan, false);

            self.accounts.principal_mint =
                AccountMeta::new_readonly(accounts.principal_mint, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.loan_collateral_vault =
                AccountMeta::new(accounts.loan_collateral_vault, false);

            self.accounts.borrower_principal_account =
                AccountMeta::new(accounts.borrower_principal_account, false);

            self.accounts.borrower_collateral_account =
                AccountMeta::new(accounts.borrower_collateral_account, false);

            self.accounts.lender_principal_account =
                AccountMeta::new(accounts.lender_principal_account, false);

            self.accounts.fee_principal_account =
                AccountMeta::new(accounts.fee_principal_account, false);

            self.accounts.principal_token_program =
                AccountMeta::new_readonly(accounts.principal_token_program, false);

            self.accounts.collateral_token_program =
                AccountMeta::new_readonly(accounts.collateral_token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.borrower.clone());

            metas.push(self.accounts.lender.clone());

            metas.push(self.accounts.fee_recipient.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.loan.clone());

            metas.push(self.accounts.principal_mint.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.loan_collateral_vault.clone());

            metas.push(self.accounts.borrower_principal_account.clone());

            metas.push(self.accounts.borrower_collateral_account.clone());

            metas.push(self.accounts.lender_principal_account.clone());

            metas.push(self.accounts.fee_principal_account.clone());

            metas.push(self.accounts.principal_token_program.clone());

            metas.push(self.accounts.collateral_token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetFeeRecipient
    // ....................................................................

    /// Main instruction struct for SetFeeRecipient
    pub struct SetFeeRecipientInstruction {
        pub accounts: SetFeeRecipientInstructionAccountMetas,
        pub data: SetFeeRecipientInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetFeeRecipient instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetFeeRecipientInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetFeeRecipient instruction
    #[derive(Debug, Clone)]
    pub struct SetFeeRecipientInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl SetFeeRecipientInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for SetFeeRecipient
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetFeeRecipientInstructionData {
        pub fee_recipient: Pubkey,
    }

    impl SetFeeRecipientInstructionData {
        pub fn new(fee_recipient: Pubkey) -> Self {
            Self { fee_recipient }
        }
    }

    /// Implementation for SetFeeRecipientInstruction
    impl SetFeeRecipientInstruction {
        fn discriminator() -> [u8; 8] {
            [227u8, 18u8, 215u8, 42u8, 237u8, 246u8, 151u8, 66u8]
        }

        pub fn data(data: SetFeeRecipientInstructionData) -> Self {
            Self {
                accounts: SetFeeRecipientInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetFeeRecipientInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetFees
    // ....................................................................

    /// Main instruction struct for SetFees
    pub struct SetFeesInstruction {
        pub accounts: SetFeesInstructionAccountMetas,
        pub data: SetFeesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetFees instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetFeesInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetFees instruction
    #[derive(Debug, Clone)]
    pub struct SetFeesInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl SetFeesInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for SetFees
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetFeesInstructionData {
        pub origination_fee_bps: u16,

        pub interest_fee_bps: u16,

        pub default_fee_bps: u16,
    }

    impl SetFeesInstructionData {
        pub fn new(origination_fee_bps: u16, interest_fee_bps: u16, default_fee_bps: u16) -> Self {
            Self {
                origination_fee_bps,

                interest_fee_bps,

                default_fee_bps,
            }
        }
    }

    /// Implementation for SetFeesInstruction
    impl SetFeesInstruction {
        fn discriminator() -> [u8; 8] {
            [137u8, 178u8, 49u8, 58u8, 0u8, 245u8, 242u8, 190u8]
        }

        pub fn data(data: SetFeesInstructionData) -> Self {
            Self {
                accounts: SetFeesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetFeesInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetPaused
    // ....................................................................

    /// Main instruction struct for SetPaused
    pub struct SetPausedInstruction {
        pub accounts: SetPausedInstructionAccountMetas,
        pub data: SetPausedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetPaused instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetPausedInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for SetPaused instruction
    #[derive(Debug, Clone)]
    pub struct SetPausedInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl SetPausedInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for SetPaused
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetPausedInstructionData {
        pub paused: bool,
    }

    impl SetPausedInstructionData {
        pub fn new(paused: bool) -> Self {
            Self { paused }
        }
    }

    /// Implementation for SetPausedInstruction
    impl SetPausedInstruction {
        fn discriminator() -> [u8; 8] {
            [91u8, 60u8, 125u8, 192u8, 176u8, 225u8, 166u8, 218u8]
        }

        pub fn data(data: SetPausedInstructionData) -> Self {
            Self {
                accounts: SetPausedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetPausedInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    /// AccountDiscriminator implementation for Config
    impl AccountDiscriminator for Config {
        fn discriminator() -> &'static [u8] {
            &[155u8, 12u8, 170u8, 224u8, 30u8, 250u8, 204u8, 130u8]
        }
    }

    /// AccountDiscriminator implementation for Loan
    impl AccountDiscriminator for Loan {
        fn discriminator() -> &'static [u8] {
            &[20u8, 195u8, 70u8, 117u8, 165u8, 227u8, 182u8, 1u8]
        }
    }

    /// AccountDiscriminator implementation for Offer
    impl AccountDiscriminator for Offer {
        fn discriminator() -> &'static [u8] {
            &[215u8, 88u8, 60u8, 71u8, 170u8, 162u8, 73u8, 229u8]
        }
    }

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    /// Program errors for memebook
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum MemebookError {
        /// Protocol is paused
        ProtocolPaused = 6000,

        /// Only the admin may perform this action
        NotAdmin = 6001,

        /// Only the pending admin may accept the transfer
        NotPendingAdmin = 6002,

        /// Fee exceeds the hard-coded maximum
        FeeTooHigh = 6003,

        /// Loan duration outside the permitted range
        InvalidDuration = 6004,

        /// APR outside the permitted range
        InvalidApr = 6005,

        /// Amount must be greater than zero
        ZeroAmount = 6006,

        /// Offer expiry must be in the future
        InvalidExpiry = 6007,

        /// min_draw cannot exceed the total principal
        InvalidMinDraw = 6008,

        /// Principal and collateral mints must differ
        IdenticalMints = 6009,

        /// Offer has expired
        OfferExpired = 6010,

        /// Offer does not have enough undrawn principal
        InsufficientOfferLiquidity = 6011,

        /// Draw is smaller than the offer's minimum
        DrawBelowMinimum = 6012,

        /// Offer still has open loans or undrawn principal
        OfferNotEmpty = 6013,

        /// Loan is not active
        LoanNotActive = 6014,

        /// Loan has already matured
        LoanMatured = 6015,

        /// Loan has not matured yet
        LoanNotMatured = 6016,

        /// Collateral mint carries a Token-2022 extension that makes escrow
        /// unsafe
        UnsafeCollateralMint = 6017,

        /// Mint account could not be parsed
        InvalidMint = 6018,

        /// Token transfer moved a different amount than expected
        TransferAmountMismatch = 6019,

        /// Arithmetic overflow
        MathOverflow = 6020,
    }

    impl MemebookError {
        /// Get the error code
        pub fn code(&self) -> u32 {
            *self as u32
        }

        /// Get the error message
        pub fn msg(&self) -> &'static str {
            match self {
                Self::ProtocolPaused => "Protocol is paused",

                Self::NotAdmin => "Only the admin may perform this action",

                Self::NotPendingAdmin => "Only the pending admin may accept the transfer",

                Self::FeeTooHigh => "Fee exceeds the hard-coded maximum",

                Self::InvalidDuration => "Loan duration outside the permitted range",

                Self::InvalidApr => "APR outside the permitted range",

                Self::ZeroAmount => "Amount must be greater than zero",

                Self::InvalidExpiry => "Offer expiry must be in the future",

                Self::InvalidMinDraw => "min_draw cannot exceed the total principal",

                Self::IdenticalMints => "Principal and collateral mints must differ",

                Self::OfferExpired => "Offer has expired",

                Self::InsufficientOfferLiquidity => "Offer does not have enough undrawn principal",

                Self::DrawBelowMinimum => "Draw is smaller than the offer's minimum",

                Self::OfferNotEmpty => "Offer still has open loans or undrawn principal",

                Self::LoanNotActive => "Loan is not active",

                Self::LoanMatured => "Loan has already matured",

                Self::LoanNotMatured => "Loan has not matured yet",

                Self::UnsafeCollateralMint => {
                    "Collateral mint carries a Token-2022 extension that makes escrow unsafe"
                }

                Self::InvalidMint => "Mint account could not be parsed",

                Self::TransferAmountMismatch => {
                    "Token transfer moved a different amount than expected"
                }

                Self::MathOverflow => "Arithmetic overflow",
            }
        }

        /// Try to convert from error code
        pub fn from_code(code: u32) -> Option<Self> {
            match code {
                6000 => Some(Self::ProtocolPaused),

                6001 => Some(Self::NotAdmin),

                6002 => Some(Self::NotPendingAdmin),

                6003 => Some(Self::FeeTooHigh),

                6004 => Some(Self::InvalidDuration),

                6005 => Some(Self::InvalidApr),

                6006 => Some(Self::ZeroAmount),

                6007 => Some(Self::InvalidExpiry),

                6008 => Some(Self::InvalidMinDraw),

                6009 => Some(Self::IdenticalMints),

                6010 => Some(Self::OfferExpired),

                6011 => Some(Self::InsufficientOfferLiquidity),

                6012 => Some(Self::DrawBelowMinimum),

                6013 => Some(Self::OfferNotEmpty),

                6014 => Some(Self::LoanNotActive),

                6015 => Some(Self::LoanMatured),

                6016 => Some(Self::LoanNotMatured),

                6017 => Some(Self::UnsafeCollateralMint),

                6018 => Some(Self::InvalidMint),

                6019 => Some(Self::TransferAmountMismatch),

                6020 => Some(Self::MathOverflow),

                _ => None,
            }
        }
    }

    impl std::fmt::Display for MemebookError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}: {}", self.code(), self.msg())
        }
    }

    impl std::error::Error for MemebookError {}

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------

    /// Custom struct: Config
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct Config {
        pub admin: Pubkey,

        pub pending_admin: Pubkey,

        pub fee_recipient: Pubkey,

        pub origination_fee_bps: u16,

        pub interest_fee_bps: u16,

        pub default_fee_bps: u16,

        pub paused: bool,

        pub bump: u8,
    }

    impl Config {
        pub fn new(
            admin: Pubkey,

            pending_admin: Pubkey,

            fee_recipient: Pubkey,

            origination_fee_bps: u16,

            interest_fee_bps: u16,

            default_fee_bps: u16,

            paused: bool,

            bump: u8,
        ) -> Self {
            Self {
                admin,

                pending_admin,

                fee_recipient,

                origination_fee_bps,

                interest_fee_bps,

                default_fee_bps,

                paused,

                bump,
            }
        }
    }

    /// Custom struct: Loan
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct Loan {
        pub borrower: Pubkey,

        pub lender: Pubkey,

        pub offer: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub loan_id: u64,

        pub principal_amount: u64,

        pub collateral_amount: u64,

        pub interest_amount: u64,

        pub start_ts: i64,

        pub maturity_ts: i64,

        pub status: LoanStatus,

        pub bump: u8,
    }

    impl Loan {
        pub fn new(
            borrower: Pubkey,

            lender: Pubkey,

            offer: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            loan_id: u64,

            principal_amount: u64,

            collateral_amount: u64,

            interest_amount: u64,

            start_ts: i64,

            maturity_ts: i64,

            status: LoanStatus,

            bump: u8,
        ) -> Self {
            Self {
                borrower,

                lender,

                offer,

                principal_mint,

                collateral_mint,

                loan_id,

                principal_amount,

                collateral_amount,

                interest_amount,

                start_ts,

                maturity_ts,

                status,

                bump,
            }
        }
    }

    /// Custom struct: LoanDefaulted
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct LoanDefaulted {
        pub loan: Pubkey,

        pub borrower: Pubkey,

        pub lender: Pubkey,

        pub collateral_claimed: u64,

        pub default_fee: u64,

        pub ts: i64,
    }

    impl LoanDefaulted {
        pub fn new(
            loan: Pubkey,

            borrower: Pubkey,

            lender: Pubkey,

            collateral_claimed: u64,

            default_fee: u64,

            ts: i64,
        ) -> Self {
            Self {
                loan,

                borrower,

                lender,

                collateral_claimed,

                default_fee,

                ts,
            }
        }
    }

    /// Custom struct: LoanOpened
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct LoanOpened {
        pub loan: Pubkey,

        pub offer: Pubkey,

        pub borrower: Pubkey,

        pub lender: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub principal_amount: u64,

        pub origination_fee: u64,

        pub principal_disbursed: u64,

        pub collateral_amount: u64,

        pub interest_amount: u64,

        pub start_ts: i64,

        pub maturity_ts: i64,
    }

    impl LoanOpened {
        pub fn new(
            loan: Pubkey,

            offer: Pubkey,

            borrower: Pubkey,

            lender: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            principal_amount: u64,

            origination_fee: u64,

            principal_disbursed: u64,

            collateral_amount: u64,

            interest_amount: u64,

            start_ts: i64,

            maturity_ts: i64,
        ) -> Self {
            Self {
                loan,

                offer,

                borrower,

                lender,

                principal_mint,

                collateral_mint,

                principal_amount,

                origination_fee,

                principal_disbursed,

                collateral_amount,

                interest_amount,

                start_ts,

                maturity_ts,
            }
        }
    }

    /// Custom struct: LoanRepaid
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct LoanRepaid {
        pub loan: Pubkey,

        pub borrower: Pubkey,

        pub lender: Pubkey,

        pub principal_amount: u64,

        pub interest_amount: u64,

        pub interest_fee: u64,

        pub lender_received: u64,

        pub collateral_returned: u64,

        pub ts: i64,
    }

    impl LoanRepaid {
        pub fn new(
            loan: Pubkey,

            borrower: Pubkey,

            lender: Pubkey,

            principal_amount: u64,

            interest_amount: u64,

            interest_fee: u64,

            lender_received: u64,

            collateral_returned: u64,

            ts: i64,
        ) -> Self {
            Self {
                loan,

                borrower,

                lender,

                principal_amount,

                interest_amount,

                interest_fee,

                lender_received,

                collateral_returned,

                ts,
            }
        }
    }

    /// Custom enum: LoanStatus
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub enum LoanStatus {
        Active,

        Repaid,

        Defaulted,
    }

    /// Custom struct: Offer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct Offer {
        pub lender: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub offer_id: u64,

        pub principal_total: u64,

        pub principal_available: u64,

        pub collateral_total: u64,

        pub min_draw: u64,

        pub apr_bps: u32,

        pub duration_seconds: u32,

        pub expiry_ts: i64,

        pub loans_opened: u64,

        pub bump: u8,
    }

    impl Offer {
        pub fn new(
            lender: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            offer_id: u64,

            principal_total: u64,

            principal_available: u64,

            collateral_total: u64,

            min_draw: u64,

            apr_bps: u32,

            duration_seconds: u32,

            expiry_ts: i64,

            loans_opened: u64,

            bump: u8,
        ) -> Self {
            Self {
                lender,

                principal_mint,

                collateral_mint,

                offer_id,

                principal_total,

                principal_available,

                collateral_total,

                min_draw,

                apr_bps,

                duration_seconds,

                expiry_ts,

                loans_opened,

                bump,
            }
        }
    }

    /// Custom struct: OfferCancelled
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct OfferCancelled {
        pub offer: Pubkey,

        pub lender: Pubkey,

        pub principal_returned: u64,

        pub ts: i64,
    }

    impl OfferCancelled {
        pub fn new(offer: Pubkey, lender: Pubkey, principal_returned: u64, ts: i64) -> Self {
            Self {
                offer,

                lender,

                principal_returned,

                ts,
            }
        }
    }

    /// Custom struct: OfferCreated
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct OfferCreated {
        pub offer: Pubkey,

        pub lender: Pubkey,

        pub principal_mint: Pubkey,

        pub collateral_mint: Pubkey,

        pub principal_total: u64,

        pub collateral_total: u64,

        pub min_draw: u64,

        pub apr_bps: u32,

        pub duration_seconds: u32,

        pub expiry_ts: i64,

        pub ts: i64,
    }

    impl OfferCreated {
        pub fn new(
            offer: Pubkey,

            lender: Pubkey,

            principal_mint: Pubkey,

            collateral_mint: Pubkey,

            principal_total: u64,

            collateral_total: u64,

            min_draw: u64,

            apr_bps: u32,

            duration_seconds: u32,

            expiry_ts: i64,

            ts: i64,
        ) -> Self {
            Self {
                offer,

                lender,

                principal_mint,

                collateral_mint,

                principal_total,

                collateral_total,

                min_draw,

                apr_bps,

                duration_seconds,

                expiry_ts,

                ts,
            }
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
